[DRAFT] Implement match group queries functions and test steps
vaticle/typedb-client-rust pull request #45
Opened 2023-05-31 07:06 UTC by dmikhalin

## What is the goal of this PR?

We implement `match group` and `match group aggregate` queries functions and corresponding BDD test steps.

## What are the changes implemented in this PR?

2023-06-12 10:13 UTC, dmitrii-ubskii requested changes
Not much to say here, well done!

2023-06-12 10:13 UTC, dmitrii-ubskii commented on dependencies/vaticle/repositories.bzl
> +#        commit = "aac5578529424bab662b7a66ca1e0419986ddc9d",  # sync-marker: do not remove this comment, this is used for sync-dependencies by @vaticle_typedb_protocol
Why? Is this a rebase error?

2023-06-12 10:13 UTC, dmitrii-ubskii commented on src/answer/concept_map_group.rs
> +// }
Let's not leave this kind of stuff in.

2023-06-12 10:13 UTC, dmitrii-ubskii commented on src/answer/numeric_group.rs
> +
Ditto

2023-06-12 10:13 UTC, dmitrii-ubskii commented on src/connection/network/proto/concept.rs
> +            concept_maps.push(ConceptMap::try_from_proto(cm)?);
`cm` => `concept_map`

2023-06-12 15:36 UTC, dmikhalin commented on dependencies/vaticle/repositories.bzl
> +#        commit = "aac5578529424bab662b7a66ca1e0419986ddc9d",  # sync-marker: do not remove this comment, this is used for sync-dependencies by @vaticle_typedb_protocol
Might be.

2023-06-15 08:43 UTC, dmitrii-ubskii approved these changes
LGTM with a minor comment.

2023-06-15 08:43 UTC, dmitrii-ubskii commented on src/connection/network/proto/concept.rs
> +        }
You're doing manually what `.into_iter().map().try_collect()` can do for you.

2023-06-15 09:16 UTC, flyingsilverfin approved these changes
Looks good! One comment, please fix before merging

2023-06-15 09:16 UTC, flyingsilverfin commented on src/connection/network/proto/concept.rs
> +        let numeric = Numeric::try_from_proto(number_proto.ok_or(ConnectionError::MissingResponseField("value"))?)?;
The error field here should be `number` not `value` right?

2023-06-15 11:42 UTC, merged